// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistence;

namespace Persistence.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20191206213817_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Domain.Models.SimpleEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastUpdateBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastUpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("simpleEntities","netCore3Test");

                    b.HasData(
                        new
                        {
                            Id = new Guid("bb3d93e8-399d-4a0a-93bb-765dbe5c44d8"),
                            CreatedBy = "Data Seeder",
                            CreatedDate = new DateTime(2019, 12, 6, 21, 38, 17, 3, DateTimeKind.Utc).AddTicks(717),
                            LastUpdateBy = "DataSeeder",
                            LastUpdatedDate = new DateTime(2019, 12, 6, 21, 38, 17, 3, DateTimeKind.Utc).AddTicks(1821),
                            Name = "TestName 1"
                        },
                        new
                        {
                            Id = new Guid("0384812c-c8f5-45f7-819a-13d737b926be"),
                            CreatedBy = "Data Seeder",
                            CreatedDate = new DateTime(2019, 12, 6, 21, 38, 17, 3, DateTimeKind.Utc).AddTicks(2908),
                            LastUpdateBy = "DataSeeder",
                            LastUpdatedDate = new DateTime(2019, 12, 6, 21, 38, 17, 3, DateTimeKind.Utc).AddTicks(2926),
                            Name = "TestName 2"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
